POST http://localhost:8080/student/login
Content-Type: application/json

{
  "ticket-number": "102460210011376",
  "name": "李博文",
  "id-number": "322085554"
}

###
GET http://localhost:8080/student/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjM0NTYiLCJpYXQiOjE1ODc4Mjg0NTYsImV4cCI6MTU4Nzg0NjQ1Nn0.BeR8bd2M2e0B7fMe4HbX_AjL1HW9A7zZmtYcZNjAzaHmZem2gjuqqxktkA_XNd8WZHAJXl3XUxeiBqC9ioYMWw

###
POST http://localhost:8080/student/choice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDI0NjAyMTAwMTM4NDAiLCJpYXQiOjE1ODg2NTYwODMsImV4cCI6MTU4ODY3NDA4M30.3cKjMWTnnvkdl8u_ufrg4TRa-C412Y6Bb49Ma1teiZGKR9EJ4dogYmQ5EuLMdA8xGGj_UrvqPwnO-kiwuXCq9g

{
  "first-choice-major": "计算机系统结构",
  "first-choice-direction": "分布式存储系统与网络",
  "second-choice-major": "网络空间安全",
  "second-choice-direction": "网络安全",
  "adjust-major": true,
  "adjust-degree-type": true
}

###
GET http://localhost:8080/student/major
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDI0NjAyMTAwMTM4NDAiLCJpYXQiOjE1ODg2NTYwODMsImV4cCI6MTU4ODY3NDA4M30.3cKjMWTnnvkdl8u_ufrg4TRa-C412Y6Bb49Ma1teiZGKR9EJ4dogYmQ5EuLMdA8xGGj_UrvqPwnO-kiwuXCq9g

###
GET http://localhost:8080/student/choices-overview
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDI0NjAyMTAwMTEzNzYiLCJpYXQiOjE1ODg2NTY0MzEsImV4cCI6MTU4ODY3NDQzMX0.7v0CH8cikGfpUOk1bl4fd_EDG1wcCknEfpZ7pDBB3ZeVL_b20mpJJh1RJOHyiNgotDgAf8ExfiaWzhzkNIhxKw

###
GET http://localhost:8080/student/files
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjM0NTYiLCJpYXQiOjE1ODc4Mjg0NTYsImV4cCI6MTU4Nzg0NjQ1Nn0.BeR8bd2M2e0B7fMe4HbX_AjL1HW9A7zZmtYcZNjAzaHmZem2gjuqqxktkA_XNd8WZHAJXl3XUxeiBqC9ioYMWw

###
GET http://localhost:8080/student/files/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjM0NTYiLCJpYXQiOjE1ODc4NzE0NDgsImV4cCI6MTU4Nzg4OTQ0OH0.Q8MsQECfsGwkKCKLc3YoRz8k7BdEE32Gy00asU5hFNer3VMaMPVcB_mT2eEv6siOZ7K-5ZTPjMJUk_Cz06yR2Q

###

