POST http://localhost:8080/student/login
Content-Type: application/json

{
  "ticket-number": "123456",
  "name": "李博文",
  "id-number": "421122199702250017"
}

###
GET http://localhost:8080/student/info
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjM0NTYiLCJpYXQiOjE1ODc4Mjg0NTYsImV4cCI6MTU4Nzg0NjQ1Nn0.BeR8bd2M2e0B7fMe4HbX_AjL1HW9A7zZmtYcZNjAzaHmZem2gjuqqxktkA_XNd8WZHAJXl3XUxeiBqC9ioYMWw

###
POST http://localhost:8080/student/choice
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjM0NTYiLCJpYXQiOjE1ODc4MDI4NzksImV4cCI6MTU4NzgyMDg3OX0.hVg-12wAvqKtVZGKO9y7G-fPOO0MB70_38LpUMxlPHX-Rxyu127MBDGbRk75d3y0GYdJvcMIG8mX4ZflmalmTw

{
  "first-choice-major": "计算机系统结构",
  "first-choice-direction": "分布式存储系统与网络",
  "second-choice-major": "网络空间安全",
  "second-choice-direction": "网络安全",
  "adjust-major": true,
  "adjust-degree-type": true
}

###
GET http://localhost:8080/student/major
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjM0NTYiLCJpYXQiOjE1ODc4Mjg0NTYsImV4cCI6MTU4Nzg0NjQ1Nn0.BeR8bd2M2e0B7fMe4HbX_AjL1HW9A7zZmtYcZNjAzaHmZem2gjuqqxktkA_XNd8WZHAJXl3XUxeiBqC9ioYMWw

###
GET http://localhost:8080/student/choices-overview
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjM0NTYiLCJpYXQiOjE1ODc4Mjg0NTYsImV4cCI6MTU4Nzg0NjQ1Nn0.BeR8bd2M2e0B7fMe4HbX_AjL1HW9A7zZmtYcZNjAzaHmZem2gjuqqxktkA_XNd8WZHAJXl3XUxeiBqC9ioYMWw

###
GET http://localhost:8080/student/files
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjM0NTYiLCJpYXQiOjE1ODc4Mjg0NTYsImV4cCI6MTU4Nzg0NjQ1Nn0.BeR8bd2M2e0B7fMe4HbX_AjL1HW9A7zZmtYcZNjAzaHmZem2gjuqqxktkA_XNd8WZHAJXl3XUxeiBqC9ioYMWw

###
GET http://localhost:8080/student/files/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjM0NTYiLCJpYXQiOjE1ODc4Mjg0NTYsImV4cCI6MTU4Nzg0NjQ1Nn0.BeR8bd2M2e0B7fMe4HbX_AjL1HW9A7zZmtYcZNjAzaHmZem2gjuqqxktkA_XNd8WZHAJXl3XUxeiBqC9ioYMWw

###

