jwt:
  token:
    validity: 18000000
    secret: FudanUniversityComputerScienceAndTechnology

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/preference-selection-software?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: libw
    password: libw521
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

