jwt:
  token:
    validity: 18000000
    secret: FudanUniversityComputerScienceAndTechnology

spring:
  datasource:
    url: jdbc:mysql://192.168.0.18:3306/preference-selection-software?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: libw
    password: libw521
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

